version: '3'
services:
  roslaunch:
    build: .
    command: tail -f /dev/null
    volumes: 
      - .:/catkin_ws/src/arena-rosnav
    environment:
      - DISPLAY=novnc:0.0
    image: arena_rosnav
    container_name: arena-rosnav
    depends_on:
      - novnc
    networks:
      - x11
    
  novnc:  
    image: theasp/novnc:latest
    env_file:
      - ./docker/novnc.env
    ports:
      - "8080:8080"
    container_name: novnc
    networks:
      - x11
networks:
  x11:
